### ISSUE TITLE
Conda install latest version of Pandas

### ISSUE THREAD

**Issue by mrocklin** [dask/dask-ec2#13]
It would be very convenient if, on top of installing Anaconda, we also conda installed a few packages.  Notably, the latest Pandas release has some very important bugfixes for parallel computing.

**Comment by pzwang** [comment]
Agreed.  However, this should be taken care of with the new Navigator - it will let people know when updates are available and they're out of date relative to the latest libs.  This would just run automatically upon first install, and prompt the user to see if they want to grab the updated packages.

**Comment by mcg1969** [comment]
Keep in mind that if you have the full Anaconda installation, you will not be able to individually upgrade packages beyond what the latest Anaconda version allows. That's because the `anaconda` conda package treats `numpy`, `pandas`, etc. as _dependencies_, hardcoded to particular versions.

That means that in order to deviate from Anaconda's "grid" of package versions, you have to do `conda remove anaconda` at some point.

Perhaps the Navigator should be smart enough to do this.

**Comment by mrocklin** [comment]
Guys, to be clear, I just need the single command run, and I need this done very quickly (dask+distributed fails hard with pandas 0.17.1).  This is also happening on a cluster, where UI elements like Navigator are not yet appropriate.

**Comment by mcg1969** [comment]
Per our internal discussion, you _will_ need `conda remove anaconda` as well, unless something changes with the `anaconda` metapackage.

**Comment by danielfrg** [comment]
Yes, i don't think the navigator comment has anything to do with this since we are not talking about a local package, this is just executing a command in all the remote nodes so they get the latest version of pandas.

This issues should be fixed in https://github.com/dask/dec2/commit/67af374acaa1bcfab3fd5f08c10fa952c1934948

**Comment by danielfrg** [comment]
All seams to be working now. Closing.
